menu:
  Home: /
  Archive: /archives

logo: Armorial Communes Basques

more:
  About Us: /about

about:
  title: Theme ACB
  link: /

show_toc_bool: true

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId: #your leancloud appId
  appKey: #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn


excerpt_num: 120

footer_info: Â© Armorial Communes Basques 2013-2018